apiVersion: apps/v1
kind: Deployment
metadata:
 name: luckynumber
 namespace: srinivas
spec:
 replicas: 1
 selector:
  matchLabels:
   app: luckynumber
 strategy:
  type: RollingUpdate
 template:
  metadata:
   name: luckynumber
   labels:
    app: luckynumber
  spec:
   containers:
   - name: luckynumber
     image: krssrinivas/luckynumber:tag
     resources:
      requests:
       cpu: "200m"
       memory: "200Mi"
      limits:
       cpu: "200m"
       memory: "200Mi"
     ports:
     - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
 name: luckynumbersvc
 namespace: srinivas
spec:
  selector:
   app: luckynumber
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000

